### ISSUE TITLE
Doesn't always load for play

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#1]
piece it together game often stays in place (pieces over their correct places) when you first encounter it. Resetting the page seems to start the game.

**Comment by iMcKelvie** [comment]
(more info) I don't think it's a caching problem, since it happens on computers that have never encountered the game before, like Thomas' laptop at the Trican meeting.

**Comment by ivanreese** [comment]
This could be an issue with the PageScrollWatcher service, or it could be in the game itself. @theseanzo, can you tackle this?

Good catch Robyn!

**Comment by iMcKelvie** [comment]
Just to follow up with this, I did a bower update and still encounter this issue on the Valve Tree Circuit, if you would like to see an example.

**Comment by crystalrubik** [comment]
This has never worked for me yet either in many modules and in all the
browsers.

*Crystal Rubik*
Designer/Animator
CD Industrial Group Inc.
···································
crystal@cdiginc.com
1-866-628-3224
www.cdiginc.com
