### ISSUE TITLE
Decoy pieces

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#14]
This isn't really an issue. It's ultra low priority - I'm just writing it down to keep track of the idea in case this game is ever revisited. 

It would be great to have an option to use decoy pieces, where they would be sucked into the bank, and available for placing, but never have a home. When all of the normal pieces have been correctly placed, the game would end with the decoy pieces still in the bank. (maybe they could fade out or something as the last correct piece is placed.) See all of the "build the valve" puzzles for an example of where this would be nice - right now the user has to discard the useless pieces into a recycling bin, and the drop zone can be a little tricky to get right.

**Comment by ivanreese** [comment]
Done.
