### ISSUE TITLE
Pieces do not randomize

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#2]
Pieces in top panel are in same order as they appear in the html. This isn't a desperate problem; now that we've noticed it we can mix up their order in the html. But it does mean the game will look identical every time it's played.

**Comment by iMcKelvie** [comment]
It also looks a little funny when you pull a piece from the middle of the bank, and an interchangeable piece rushes over to fill its spot. This won't be noticeable in 99% of the games; it's only obvious in the version in process control valves, where there are only symbols of two types.

**Comment by ivanreese** [comment]
This sounds like a missing feature. It's probably coming.

We will *always* want items to be randomized, right? I can't conceive of a case where we might want the order of elements to be determined by source order in the HTML.

**Comment by iMcKelvie** [comment]
Yeah, if it is possible!

 I don't think we've made a case yet where pieces should not be randomized.
