### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by crystalrubik** [cdig/piece-it-together#3]
Symbols are in place in the top bar, but are not draggable. Detects activity and won't let you by, but you can't play. 

Windows 7, IE 11
Trican Acid Unit, Process Control Valves, Drag 'n' Drop

**Comment by ivanreese** [comment]
Just a note while I'm here: please change the name of the pages where the game is used to match the new name, Piece It Together. We need to give all of our games "proper noun" names from now on, and use them consistently. So any pages named or titled something derived from "drag and drop" or "matching game" need a swift kick in the right direction ;)

**Comment by iMcKelvie** [comment]
Let's not use those names at all (at least, where the customer sees them). I think we should strive for names that are meaningful to the content. (And I know this was my writing in the first place, so my fault.) Names should describe what you're doing. E.g.: Label the Valve Tree, or Build The Circuit, or ID the Valve. Everyone who reads this, if you come across a "Matching" or "Drag 'n' Drop" Heading, please change it accordingly.

**Comment by theseanzo** [comment]
Hey, can you let me know if this is still happening? I've tested in IE and it seems to be resolved.

**Comment by crystalrubik** [comment]
​It starts up perfectly with the other issue you fixed (pieces start in
place and move to the top when you get to the page now), but you still
can't click and drag on the symbols.

Trican Acid Unit, Process Control Valves
IE11​, Windows 7


*Crystal Rubik*
Designer/Animator
CD Industrial Group Inc.
···································
crystal@cdiginc.com
1-866-628-3224
www.cdiginc.com

**Comment by ivanreese** [comment]
I was going to guess pointer events! Good stuff.

Also, you probably know this bug just in case... when you're referring to issues from commit messages, you can also say "close", "fixes", or "fix".
