### ISSUE TITLE
Does not work on touch screens

### ISSUE THREAD

**Issue by crystalrubik** [cdig/piece-it-together#4]
Can't drag the pieces on phone. It just wants to scroll the page. 

Trican Acid Project, Displacement Tanks and HF Hopper (or any piece it together game), Identify the Valves
Safari, iPhone 5S, iOS 8.1.3

**Comment by ivanreese** [comment]
AFAIK, that's not a bug, it's just that doing touch input is new and hard and Sean probably hasn't done it yet.

**Comment by theseanzo** [comment]
Yeah, I haven't done anything to enable dragging them on touch screens. I'm changing this to a feature, as having dragging work on touch screens isn't an easy thing to add.

**Comment by ivanreese** [comment]
Definitely something that will get easier once we've done it a few times and have figured out the best way.
