### ISSUE TITLE
Pieces move position

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#5]
I'm not certain whether this is actually a bug, or whether it's a symptom of the "does not load for play" issue.

When the game does not load for play, many of the pieces are shifted from their targets. As soon as I comment the cd-activity out, the pieces are positioned correctly again. My guess is that they were starting to collect up for positioning in the panel, but stopped after moving a tiny distance. Hopefully this will be resolved with the other bug, but I thought I'd post it anyway, in case it gives a clue as to what's going on. (For an example, see the game in Valve Tree (Circuits)).

**Comment by theseanzo** [comment]
This should be fixed. If you see it again, let me know. What was happening is that, when the page was hidden behind a locked page, the position to place the elements was being calculated incorrectly due to the elements being in the DOM but not shown.

**Comment by ivanreese** [comment]
Good catch!

**Comment by iMcKelvie** [comment]
Thanks, Sean!!

On Thu, Mar 12, 2015 at 6:39 PM, theseanzo <notifications@github.com> wrote:

> This should be fixed. If you see it again, let me know. What was happening
> is that, when the page was hidden behind a locked page, the position to
> place the elements was being calculated incorrectly due to the elements
> being in the DOM but not shown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdig/piece-it-together/issues/5#issuecomment-78718203>
> .
>



-- 
Robyn Hoffman
Designer/Animator
CD Industrial Group Inc.
···········································
robyn@cdiginc.com <robyn@carldyke.com>
Ph: 1·866·628·3224
www.cdiginc.com <http://www.carldyke.com/>
