### ISSUE TITLE
Prepend vs. append

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#7]
This is a request to add to the documentation on Piece It Together.

The code example asks us to add 

# @codekit-prepend '../bower_components/piece-it-together/dist/piece-it-together.coffee'

If the previous line to bring in scripts starts with append, not prepend, you need to change one of the lines so that both are the same, or things get soooooo broken.

**Comment by ivanreese** [comment]
Yes. We talked about this once a while back in one of those "hey guys, make sure you always do this" informal sessions around the office. I should have taken the time to write it down somewhere. Sean and I talked about this a few weeks back, and I thought he said he was going to remind everyone or something, but I can't remember.

The rule is: *always* use prepend — *never* use append. Applies to all things. If you see `append` used anywhere, please report it to the nearest -brownshirt- Sean or Ivan.

**Comment by ivanreese** [comment]
@theseanzo @crystalrubik @Nathanoid heads up.
