### ISSUE TITLE
setting width and height

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/piece-it-together#8]
Hey, guys, another request to add to the documentation. This isn't directly related to the code; I was hoping to add it as a useful suggestion for implementation.

When using piece it together with text (e.g. labelling components is a really common one), it can be helpful to set a min-width and min-height (in percent) on the div containing your text, to create a larger object. This makes it easier for the user to "hit" the drop target.  As an example, here are the rules I like to add to each of my little text tags.

  .light{
    display:flex;
    align-items:center;
    justify-content: center;
    min-width:19%;
    min-height:5%;
  }

**Comment by ivanreese** [comment]
Rather than use Flex and min sizes, can you just use display: inline-block and some padding?

**Comment by iMcKelvie** [comment]
Yes, you can get nearly the same effect, except that flex handles the
spacing nicely. With padding, I need to be sure to pick a larger number for
padding than half of the min height to get the text to centre vertically. I
thought flex was less complicated, and I've had good results testing
cross-browser. Is there a reason to avoid using it?

On Thu, Apr 2, 2015 at 11:54 AM, Ivan Reese <notifications@github.com>
wrote:

> Rather than use Flex and min sizes, can you just use display: inline-block
> and some padding?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdig/piece-it-together/issues/8#issuecomment-88991017>
> .
>



-- 
Robyn Hoffman
Designer/Animator
CD Industrial Group Inc.
···········································
robyn@cdiginc.com <robyn@carldyke.com>
Ph: 1·866·628·3224
www.cdiginc.com <http://www.carldyke.com/>

**Comment by iMcKelvie** [comment]
Sorry, I see you had asked me to avoid min sizes as well. No, I don't get the same result doing that; I'm trying to create a div that fits nicely into a box onscreen, and shrinks and grows as the image shrinks or grows on resize.

**Comment by iMcKelvie** [comment]
See the drag and drop from the Centrifugal pumps module (almost at the end) for an example.

**Comment by ivanreese** [comment]
I won't have wifi for another month (rural Spain), so I can't check anything in the Dropbox. My thought was just looking for something simpler. Flex and min are both one notch higher into complexity than I'm usually comfortable with, but that's just personal heeby-geebies.

**Comment by ivanreese** [comment]
Now that we are using wikis for documentation that goes beyond "how to get started", this is very much the sort of info that belongs in a wiki page. Robyn, would you be okay if I started a wiki page with your pasted style snippet, and closed this issue?

**Comment by iMcKelvie** [comment]
wow - I completely can't even remember typing this, or what was going on.
But yes, feel free to shuffle it to a wiki!

On Wed, Jun 24, 2015 at 5:58 AM, Ivan Reese <notifications@github.com>
wrote:

> Now that we are using wikis for documentation that goes beyond "how to get
> started", this is very much the sort of info that belongs in a wiki page.
> Robyn, would you be okay if I started a wiki page with your pasted style
> snippet, and closed this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdig/piece-it-together/issues/8#issuecomment-114843919>
> .
>



-- 
Robyn Hoffman
Designer/Animator
CD Industrial Group Inc.
···········································
robyn@cdiginc.com <robyn@carldyke.com>
Ph: 1·866·628·3224
www.cdiginc.com <http://www.carldyke.com/>
